#+title: Notes Projet Long
* Papers
** Museum
Histoire et détail du domaine - depuis 1987.
en général on identifie le smFISH (single molecule) comme le début, fin 90s. Ici on recule en 1987. Se base sur la littérature et une base de données créée pour l'occasion.
*Définition* : attempts to quantify mRNA expression of large number of genes within the spatial context of tissues and cells. Criticable : pas d'aspect a priori dans la définition.

To ce qui est trapn hybridization a été utile pour créer des bases de données de référence.

WM ISH a été important mais était contraignant et a été progressivement abandonné dans les années 2010, étant en particulier assez qualitatif.

*** How is spatial information acquired? :
- Region of Interest selection : physical and optical mapping of ROIs for isolation. ensuite analysés via RNA-Seq/scRNA-seq. Ex Tomo-seq. Comment micro disséquer ? La plupart du temps en LCM = laser capture microdissection. Can harvest cells of interest. Can even be used to reconstruct in 3D. Optical mapping : using transgenic mices, photoactivatable GFP, the FACS. Plus populaire : Nanostring GEoMX et whole transcriptome atlas : fonctionne avec des panels, avec jusqu'à 18000 gènes.
- smFISH : highly multiplexed, started in 2012. À la base nécessitait de la super-resolution microscopy. On peut activer les probes une par une, on arrive à 4 colours et 8 rounds. Ce qui fait beaucoup. Il y a aussi le MERFISH. Gene encoded by binary code. Pb : plus on a de gènes suivis, plus il y a de l'optical crowding, et d'autres soucis.
- in situ sequencing : sequencing by ligation/gene barcodes/short fragments in situ.
- ngs with spatial barcoding (visium?) : in situ arrays that capture transcripts. No single cell resolution. spots in Visium are 100µm center to center, and slide seq is smaller, as well as Stereo seq.
- methods not requiring a priori spatial location : for rare cell types.



Also : multi omics ! Withy oligonucleotide tagged antibodies to detect proteins of interest, chromatine structure with MERFISH and seqFISH+. Of interest for ANR : electroseq.


*** Goals and tradeoffs :
- transcriptome wide profiling (j'imagine pas d'a priori)  : ROI ou NGS sont sans a priori, mais détectent relativement peu, tandis que des panels type smFISH+ et MERFISH peuvent quantifier 10 000+ gènes mais rien de non connu (et probablement pas top pour des organismes non modèles, puisque les probes ne doivent pas exister !). Mais même smFISH ça peut-être très compatible avec le scRNA-seq, mais comme 10X le vend pas...
- single-cell resolution (se)   : ici le smFISH- et le ISS est bien résolu, pas le reste.
- high gene detection efficiency (profond - pas comme visium) : dur d'avoir une idée du ground truth, mais smFISH sur un panel est le moins pire. Highly multiplexed smFISH are quite good in this area. Entre 6 et 15 % d'efficiency pour le Visium. Le scRNA-seq c'est entre 3 et 25% (seulement? Même en SMART?)
- Tissue area : usually goes against detection efficiency.
- Usability : most techniques developped for frozen tissue, some are FFPE compatible. Les fish sont assez peu compatible avec le FFPE, Visium l'est mais avec un certain coût niveau détection de gène, divisé par 5 à 10. Visium se répand plus vite que smFISH, notamment parce que le dernier est cher, fluidique complexe, bcp de temps d'imaging...
- Upstream data-analysis : en FISH c'était souvent mal écrit en Matlab, mais ça change. Pairer avec le single cell est potentiellement intéressant pour fish ou ISS, car les gènes qui ne sont pas dans le panel peuvent se retrouver dans les données sc. Pour les autres techniques qui ne sont pas single cell : negative binomial models (stereoscope), Poisson (simpler, RCTD) and NNLS (non-negative least squares). Non negative matrix factorization also, for instance spotlight. Certains font des parallels avec le texte mining : cells = topics, genes = words, LDA for topix modeling a pu être appliqué comme avec STRIDE et STdeconvolve (unsupervized, no scRNA-seq needed).
- Downstream data-analysis : focused on count matrixes of cells/spots. Souvent compris dans les suites telles que scanpy et seurat. Il y en a aussi des dédiés, tels que Giotto, STUtility. Seurat et Giotto implémentent aussi des fonctions basiques pour faire de l'identification de spatial variable genes. Ensuite, pour trouver les spatial variable genes, on trouve 3 approches principales
  1. Gaussian process regression + generalization to Poisson and NB : modélisation de l'expression génique comme GPR avec et sans la donnée spatiale. Can be time consuming, especially with MCMC.
  2. Laplacian score : identify genes whose expression better reflects the structure of a spatial neighborhood graph. Permutation testing can also be time consuming.
  3. Moran's I. Utilisé par Seurat v3.
  On peut aussi chercher les interactions entre cellules, via des paires ligand recepteur. Quelles paires peuvent être plus exprimées.
  Autres applications : archetypal gene patterns, spatial regions defined by transcriptome...


*** Trends in spatial transcriptomics field
lack of unified databases.
The field is very limited to human and mice!!

*** Museum : online details

**** Cell type deconvolution
